services:
  reastuant:
    build: .
    depends_on:
    - redis
    networks:
    - front-tier
    - back-tier
    environment:
    - DB_HOST=redis
    - DB_PORT=6379
    restart: unless-stopped

  redis:
    image: redis:7.2.3-alpine3.18
    networks:
    - back-tier

networks:
  front-tier:
  back-tier: